### ISSUE TITLE
Post to reddit notification

### ISSUE THREAD

**Issue by jaquelynesulhoff** [KenEucker/biketag-website#103]
Can we have a little pop-up after someone posts on the website hosting the text ready for a C+P into Reddit?

It can say Want to Post to reddit? Copy this text into a new post.

**Comment by KenEucker** [comment]
I'm thinking that this could actually be accomplished via the buttons that show up after a successful upload. We could provide messaging like:

"Would you like to post to Reddit with your own account?

*This BikeTag game has enabled automatic posting of each BikeTag to Reddit on the r/[subreddit] subreddit. These BikeTag posts are created for users to be able to have a discussion with other users about each tag. Unless you click the button to post the BikeTag yourself, the post will be created on your behalf by u/[user] crediting you by name."

And show two buttons: 

I'll Post It Myself --> disables auto-posting to Reddit, so pee shows a new card with the template filled out for them.

Post For Me! -> closes the modal and auto-posts to Reddit.

Edit: Changed the button text given feedback

**Comment by jaquelynesulhoff** [comment]
This is great! Maybe instead of All Good we say “crosspost for me” so its
extra clear

**Comment by KenEucker** [comment]
This biketag-website project is now sunsetting.
