### ISSUE TITLE
"Play" button's text overflows on 16:9 displays

### ISSUE THREAD

**Issue by jasonli468** [KenEucker/biketag-website#109]
On mobile devices, the button simply says "Play" along with the number of the next round, but on 16:9 displays, the button tries to fit "Play the next round" along with the number in the same area so the text massively overflows. Easiest fix I see is to just make desktop text to match the mobile text, I'd make the change myself but I couldn't find the file where this logic happens.

**Comment by KenEucker** [comment]
@jasonli468 this is intended wording, as the screen gets smaller we remove text from the button. On the smallest screen it will say "Play (#243)", on the largest it will say "Play the next round (#243)".

Though, it doesn't have to be this way. I'd love to see a screenshot of what you're seeing at 16:9 with the overflowing text.

**Comment by jasonli468** [comment]
Seems to be fixed now, before it the button was the same size as the Archive or How To buttons and the text overflowed out of the box as 4 rows when the button could only fit one. Now, the button is about twice as wide and tall and all the text fits within two rows inside the button.

**Comment by KenEucker** [comment]
Thanks @jasonli468, for following up! I'm glad that things are looking better on your 16:9 screens. I'm also working on the image ratio fix you mentioned in your PR, and will have that up on the site soon.
