### ISSUE TITLE
Add prettier for consistent code formatting

### ISSUE THREAD

**Issue by benaduggan** [KenEucker/biketag-website#145]
Hey there! 

I wanted to get started contributing to the repo and saw there wasn't much consistency in the formatting. 

I've been really getting into prettier. The format on save support in almost all editors makes it really easy to make a project consistent with minimal effort. 

I created this PR #144 to add support!

also, I hate to be that guy, but part of wanting to get started contributing is [Hacktoberfest](https://hacktoberfest.digitalocean.com/) and I was wondering if you'd be willing to add "hacktoberfest" to the topics!

<img width="658" alt="image" src="https://user-images.githubusercontent.com/5338872/95021317-4f1d6e80-063e-11eb-974f-c8964724a458.png">

**Comment by KenEucker** [comment]
hacktoberfest topic added, and this PR was merged. Thanks!
