### ISSUE TITLE
Startup bug: "Error: secret option required for sessions"

### ISSUE THREAD

**Issue by benaduggan** [KenEucker/biketag-website#147]
Newbie here again. When I first set up the app I was running into this error.

<img width="1024" alt="image" src="https://user-images.githubusercontent.com/5338872/95025421-a419ae80-0657-11eb-9f1e-2fb0e1d13fd0.png">

In an attempt to track it down I found [this line](https://github.com/KenEucker/sexpress/blob/b0394c9dabce5c48f5eee1622dcf0edd30853692/lib/sexpress.js#L487) in the sexpress library which seems to imply we need to set the `appName` in the config. So I made a PR adding `appName` to the sample.config.json which seems to have fixed it!

PR here! #146

**Comment by KenEucker** [comment]
@benaduggan this is a bug within the sexpress library, which should be rectified there. I encourage you to head over to the project repository and create the PR that would prevent such an error from occurring or to provide an error message that is more helpful.

https://github.com/KenEucker/sexpress

**Comment by benaduggan** [comment]
👍 I'll check it out! 

Just to clarify on the contribute section of the readme, would it be better for me to start with creating an issue then gather discussion and consensus and then start on a PR? I think I read the section to mean to create a PR and a corresponding issue all at once, but now that does seem a little redundant.

**Comment by KenEucker** [comment]
@benaduggan the list of ways to contribute in the README are suggested ways to contribute. You don't have to do all of them. Starting with an issue is a good place to see whether or not a PR would be helpful to the project.

Furthermore, a single line change to a configuration sample is not a meaningful contribution to the project worth creating a PR for, in my opinion. While it is appreciated that others take advantage of Hacktoberfest to help out, sifting through PRs like that is more work for the maintainers.
