### ISSUE TITLE
Instagram link in the footer opens in same tab and deletes history

### ISSUE THREAD

**Issue by benaduggan** [KenEucker/biketag-website#148]
Just noticed this while browsing the site, but if you click around so that you have a browser history, and then you click on the instagram link, it'll open in the current tab and destroy your history so you can't go back to the site.

![Screen Recording 2020-10-06 at 10 48 22 PM](https://user-images.githubusercontent.com/5338872/95282024-80f12980-0826-11eb-8f59-07b20e2ffc3c.gif)

**Comment by KenEucker** [comment]
This is sort of a weird issue that I'm not seeing consistent behavior with on my machine. I'm certain that it has to do with the biketag template and how it tracks the history, but it also uses push state so I'm not sure why this would occur.

Nevertheless, the impact is probably pretty low. I would happily accept a PR on this if you sort it out.

**Comment by selator** [comment]
I tried to reproduce this with Chrome (MacOS), Firefox (MacOS and Android) and Safari (MacOS), but couldn't.

**Comment by benaduggan** [comment]
Hah! I dug into it a bit more and realized that the "Facebook Container" extension on Firefox is causing this behavior. 

I do think it makes sense to open these links in new tabs though? What would y'all think about making all external links open in new tabs with `rel="noreferrer noopener"` for a bit of added privacy/security?
