### ISSUE TITLE
Weird bug with the next round's number

### ISSUE THREAD

**Issue by selator** [KenEucker/biketag-website#162]
Depending on whether I open the page or come back from archive/tagit state, I see different numbers for the next round's number. See the two screenshots.
![56](https://user-images.githubusercontent.com/5841311/101277480-06587200-37b5-11eb-8023-5c64e15614f6.png)
![57](https://user-images.githubusercontent.com/5841311/101277482-08223580-37b5-11eb-9d62-ed9237fc52c7.png)

**Comment by KenEucker** [comment]
@selator this bug has been fixed!
