### ISSUE TITLE
Add user badges/awards

### ISSUE THREAD

**Issue by KenEucker** [KenEucker/biketag-website#166]
You just unlocked...
"First tag ever!"
"10th tag"
"Back to back tag"

For users who "log in"

**Comment by steve-kasica** [comment]
It'd also be cool to have achievements like *fastest finder* and *best hider* for who plays a biketag with the shortest turnaround time or has a biketag go unfound the longest.

**Comment by KenEucker** [comment]
@swkasica I like the idea of those achievements because they would encourage a regular pace of playing the game. I do have some concerns, though, and I think we could talk through those concerns and come up with a good solution.

For the higher paced regions, I would worry that this information would be both inadequate/incorrect but also drive an even faster pace than already exists for those users who are seeking to "steal" a badge from another user.

These are the sort of considerations that we make when adding new things to the game. These badges or achievements are intended to create more of a level playing field when it comes to the rewards of the game. Again, for the faster paced games like Seattle or Vancouver, the pace actually keeps rewards away from other casual players who may not have the time or energy to "win" a round. 

We want everyone to be able to join in and feel like they are playing BikeTag, and that the competitive nature only fosters more engagement not hinders players from feeling included.

**Comment by KenEucker** [comment]
Badges will be implemented in the new BikeTag App post release.

This biketag-website project is now sunsetting.
