### ISSUE TITLE
Order the list of regions on the homepage by the most recently posted

### ISSUE THREAD

**Issue by KenEucker** [KenEucker/biketag-website#168]
On the homepage of the app, where we list out all of the regions (currently in the order of when they became a BikeTagOrg supported region), we could shuffle this list based on the most recently posted region. We could do this after the images load and order the list in realtime (based on the image data returned from imgur).

**Comment by HansInDuncan** [comment]
I would prefer to see each location listed alphabetically. Especially, as more and more locations are added, this would help site visitors in quickly finding the game location of interest.

**Comment by KenEucker** [comment]
@HansInDuncan noted. 

We can certainly add ways to filter by alphabetical, recently posted, or by creation date.

**Comment by HansInDuncan** [comment]
That would be the ideal. Great idea!

Take care,
Hans

**Comment by KenEucker** [comment]
This biketag-website project is now sunsetting.
