### ISSUE TITLE
The auto-posting button should include the tag number in case there's at least 2 tags in the queue.

### ISSUE THREAD

**Issue by selator** [KenEucker/biketag-website#173]
Currently if I have 2 unposted tags, the buttons from both will post the last one.

**Comment by KenEucker** [comment]
@selator 

I KNOW, gah. This issue is the current struggle of mine as well. I am motivated to include this in the upcoming release, I just need to fix a range of items before small fixes can go out. Sorry about the inconvenience in the meantime.

**Comment by KenEucker** [comment]
@selator this has been fixed! the individual emails will post the individual tags that they are intended to post. So an email for #188 will post 188 while an email for #189 will post 189. 

Additionally, the button can be pressed any number of times and if the tag has already been posted to Reddit then it won't post again.

Yay!
