### ISSUE TITLE
Security vulnerability disclosure is unclear.

### ISSUE THREAD

**Issue by jguddas** [KenEucker/biketag-website#180]
I stumbled across a security vulnerability and have send an email to hello@keneucker.com containing the details.

I hope that we can clear things up for the future by providing a security policy.

https://github.com/KenEucker/biketag-website/security

**Comment by KenEucker** [comment]
@jguddas nevermind, I found it. It was in the spam folder?

**Comment by KenEucker** [comment]
This biketag-website project is now sunsetting.
