### ISSUE TITLE
Design: finalize spoke cards and stickers

### ISSUE THREAD

**Issue by ellenwest** [KenEucker/biketag-website#27]
- [x] Lets finalize badass designs for our spoke cards and stickers. 
- [x] Once the designs are final, we can send them to Sticker Ninja to be printed.

Due date: ASAP
Deliverable date: by 6/21

**Comment by ellenwest** [comment]
We are awaiting designs from outside sources from Horrible Logos and our designer, https://whawkins.co

**Comment by KenEucker** [comment]
HorribleLogos responded to my request with this awesomeness:

Image:
![bike-tag (1)](https://user-images.githubusercontent.com/1720267/82736123-0c38ab00-9cdc-11ea-81b6-71765ec4ad6d.jpg)

Jingle:
https://drive.google.com/open?id=1UMTSCIlZq9HmIWLNrEgfvtn1j7R2C7iN

**Comment by evan-white** [comment]
HorribleLogos responded to my request with the PDXBikeTagOrg design!:
![pdx-bike-tag](https://user-images.githubusercontent.com/64663106/82736774-ebbf1f80-9ce0-11ea-9c54-dc7b4fdccbd8.jpg)
Here are three logo draft ideas:
![BikeTagOrg Idea 3](https://user-images.githubusercontent.com/64663106/82736432-9d108600-9cde-11ea-9101-0ade7613736c.png)
![BikeTagOrg Idea 1](https://user-images.githubusercontent.com/64663106/82736435-a00b7680-9cde-11ea-8212-9689680fdb79.png)
![BikeTagOrg Idea 2](https://user-images.githubusercontent.com/64663106/82736436-a0a40d00-9cde-11ea-8dcc-a45b7fe37af8.png)

**Comment by evan-white** [comment]
![Pixel2](https://user-images.githubusercontent.com/64663106/82834836-2490fd00-9e77-11ea-82a6-91d0124d5b71.png)

**Comment by KenEucker** [comment]
@evan-white looks good! Some final feedback/suggestions from me:

Maybe make the bikes in the background grey/black? I think it would make the pink on pink and green on pink situation clash less. 
I also wonder if it might be possible to play with the hue of some of the letters to make them pop out from the background more? The K, E, R, the blue G stand out the most to me while the gapped blocks in the B T and O make those letters harder to read.

I like the shape around the letters, do you think that this is a design that will sit well in a spoke?  We could also have a curved one? I'd love to have this curve along the rim as a spoke card!

**Comment by evan-white** [comment]
@KenEucker thanks for the feedback! I think part of the inspiration for this particular design came directly from the pink background with the lighter pink bikes, so if looking at some different color choices I'd like to try working with the letter colors before the background color. Regarding the B T and O letters, they do have the most negative space, so I will try juxtaposing the brightest colors to place on those three letters. Hopefully, this will make the other letters sit a bit better with the B T and O letters forming a more cohesive look.

As far as curvature goes, yes, absolutely we can curve this entire logo! I'll upload re-colorized and curved drafts.

**Comment by evan-white** [comment]
![Pixel4](https://user-images.githubusercontent.com/64663106/82845345-05a36280-9e99-11ea-8252-673d57794477.png)

Okay, so I tried to stick with what I wrote above, but Deb weighed in ultimately leading to this design. We now have a new color palette and made changes to the angles of the lettering. Unless anyone disagrees, this design will become a limited run of 50 8"x1.5" stickers made by stickerninja.com

**Comment by evan-white** [comment]
![Pixel Spoke Card](https://user-images.githubusercontent.com/64663106/83183753-38d63380-a0dd-11ea-9edc-943ffba58d3b.png
Here is the same design curved into a spoke card.

**Comment by KenEucker** [comment]
And now we have a denver logo:
![denver-bike-tag](https://user-images.githubusercontent.com/1720267/83346568-5f10f480-a2d2-11ea-8b9e-4a4e694d2ae9.png)

**Comment by evan-white** [comment]
Orders have been placed:
5/25 - Neon 3D logo. Size 5.5"x1.5". Quantity of 50. Received 6/5.
6/12 - Horrible Logos general logo. Size 3"x2". Quantity of 50.

**Comment by evan-white** [comment]
Set Spoke card poker playing cards ordered. Delivery expected 6/22
![unnamed](https://user-images.githubusercontent.com/64663106/85078851-3f0a7d80-b17a-11ea-8f19-1c462bf8b8b7.jpg)
.

**Comment by ellenwest** [comment]
These are dope!
