### ISSUE TITLE
Content: write BikeTag 'Narrative'/'Story'

### ISSUE THREAD

**Issue by ellenwest** [KenEucker/biketag-website#30]
Possibly a mission/vision statement for who we are and what we hope to accomplish?

**Comment by evan-white** [comment]
BikeTag: Bike. Discover. Share

Mission statement ideas:
To create the most straightforward and fun image-based location finding games for explorers.
Offer open and simple games to challenge adventurers.
Play games while biking and hiking.

Vision statement ideas:
To help every explorer around the world find unique and interesting destinations.
Making bicycling and hiking more fun for everyone.
Challenging the idea that knowing one’s destination encourages the journey.

**Comment by evan-white** [comment]
What can/does BikeTagOrg accomplish?

BiketagOrg seeks to do the following:
Become an authority for a game we work to further define.
Be a place to present ideas that make the game more organized and streamlined.
Expand the BikeTag platform to be applied across multiple modes of transportation, as well as scalable to a global level.
Create a purposeful design interface that is specifically tailored to play the game.

**Comment by KenEucker** [comment]
The BikeTag "Narrative" exists on biketag.bike.

This biketag-website project is now sunsetting.
