### ISSUE TITLE
Content: draft the 'How to' for our ambassador program

### ISSUE THREAD

**Issue by ellenwest** [KenEucker/biketag-website#31]
‘Poop sheet’ explaining:

- [ ]  the basics of the program

- [ ] the assistance we can provide (eg collateral like postcards, spokecards, building out the regional subdomain, etc.)

**Comment by ellenwest** [comment]
We have completed a draft, needs to be fleshed out more.

**Comment by evan-white** [comment]
This has been updated and is mentioned in #36 about playbook creation. 
We now have a document and checklist for onboarding ambassadors in our Ambassador Resources documents titled "Ambassador Program Checklist and Template"

**Comment by KenEucker** [comment]
This biketag-website project is now sunsetting.
