### ISSUE TITLE
Content: write Terms of Service/Code of Conduct

### ISSUE THREAD

**Issue by ellenwest** [KenEucker/biketag-website#33]
Considerations:

- [ ] - User Data

- Usage on social media

- Usage on BikeTag.org 

- Usage on Reddit

- [ ] - Publishing of images, geotags, etc.

- Refer to imgur's terms of use as well?

- [ ] - Safety: our advice and guidelines

**Comment by KenEucker** [comment]
We have a conduct document now, but we still need a terms of service.

https://github.com/KenEucker/biketag-website/blob/production/CONDUCT.md

**Comment by KenEucker** [comment]
The terms of service was written in December of last year:

https://biketag.bike/2021/12/31/biketag-terms-of-service/

To note, for those who think they can send us a DMCA, this is from Reddit's API TOS but I expect the same exact language in the other integrated API TOS documents.

> d. User Content. Reddit user photos, text and videos ("User Content") are owned by the users and not by Reddit. Subject to the terms and conditions of these Terms, Reddit grants You a non-exclusive, non-transferable, non-sublicensable, and revocable license to copy and display the User Content using the Reddit API through your application, website, or service to end users. You may not modify the User Content except to format it for such display. You will comply with any requirements or restrictions imposed on usage of User Content by their respective owners, which may include "all rights reserved" notices, Creative Commons licenses or other terms and conditions that may be agreed upon between you and the owners.

(https://www.reddit.com/wiki/api-terms)
