### ISSUE TITLE
Content: build Bike Tag playbooks

### ISSUE THREAD

**Issue by ellenwest** [KenEucker/biketag-website#36]
We need playbooks for the following regional biketag features
These playbooks will guide the regional ambassadors through running the version of Bike Tag they wish to see in their city:

BikeTag website (completed)
Reddit (completed)
Instagram
Imgur
Github
Ambassadorship Program (completed) 
Development

**Comment by evan-white** [comment]
These three playbooks have been completed and have been sent to ambassadors in Denver, Omaha, Indianapolis, and Seattle:
BikeTag App (website)
Reddit
Ambassadorship program

**Comment by KenEucker** [comment]
This biketag-website project is now sunsetting.
