### ISSUE TITLE
Regional landing page

### ISSUE THREAD

**Issue by ellenwest** [KenEucker/biketag-website#42]
* Show active Biketag cities on the map 
* Explain and invite people to get BikeTag started in their own city via the ambassador program if their city isn’t already participating

**Comment by KenEucker** [comment]
The regional landing page has been created and deployed to the site. This ticket will remain open until a better design for this page has been approved and we complete the rest of the tasks on this issue.

**Comment by KenEucker** [comment]
A template has been chosen for this page. The items listed in this ticket can be broken out into new tickets as part of a larger site redesign. Closing this ticket for now.
