### ISSUE TITLE
Implement new Nav design

### ISSUE THREAD

**Issue by ellenwest** [KenEucker/biketag-website#46]

**Comment by evan-white** [comment]
![Website design idea 5_1_20](https://user-images.githubusercontent.com/64663106/82705314-506c7280-9c2c-11ea-9cb3-4978929b8c02.png)

**Comment by KenEucker** [comment]
There is a discussion happening over at Reddit that is relevant to this ticket:
https://www.reddit.com/r/CyclePDX/comments/gpztja/bike_tag_205/

A user provided this image:
![image](https://user-images.githubusercontent.com/1720267/82781033-a6e4d700-9e0d-11ea-9d68-1edd1de4799c.png)

And this feedback:

> Here is how I would envision the biketag.org page that the reddit post links to to look in the way that would be most useful to me: https://imgur.com/a/L9Ck2nD
>
> both pics would still be hosted by imgur, and then when you go to view 10/50/all, the pics each user took are next to each other (X Proof next to X+1's mystery spot)
>
> The advantage to me is that you can go back in time and sort of imagine the ride that someone went on that includes those two points. and on top of that, I don't have to: click link -> go to post -> click back -> go to proof post to see hint-> go back. The flow is just: click link, see new post, the hint, and the proof post, and read up on the rules if I forgot them. Just one link to click simplifies things a lot, IMO
>
>One thing I am noticing though is that each post doesn't have its own permalink like say... a reddit comment does, so at the moment I'm guessing navigating from one tag to the next isn't really feasible, as the only tag that has its "own" url is the one on the home page.
>
>One more piece of feedback, the rules link isn't linking to the rules for me, the biketag.org/#howto with the city subdomain upfront just sends you to the biketag.org homepage.

**Comment by KenEucker** [comment]
Closing this now as we've reviewed it and the team is happy with where we are. We still need the brand styling in #96 to be finalized to finish the polish of this work, but so far as what the intention of this issue is: we've accomplished that.
