### ISSUE TITLE
Add city name as header for each subdomain

### ISSUE THREAD

**Issue by ellenwest** [KenEucker/biketag-website#48]
Each city subdomain (eg pdx.biketag.org) should have a header that states the city name and labels the feed. 

Benefits:
* User does not have to look in the URL 
* Stronger sense of place
* Signals that this is a multi-city game

**Comment by KenEucker** [comment]
The `tagline` field has been added to the /data/config/subdomains.json for the "header" to be added to the templates.

**Comment by ellenwest** [comment]
It's possible that we could replace the current bike icon with the regional icons created by Horrible Logos in the header of each Bike Tag game.

For example, replace the simple white bike graphic and with the PDX horrible logo on portland.biketag.org.

![image](https://user-images.githubusercontent.com/65753068/83346806-85d02a80-a2d4-11ea-996c-425c27a56727.png)

![image](https://user-images.githubusercontent.com/65753068/83346817-9e404500-a2d4-11ea-98e6-9d482b75841a.png)

**Comment by ellenwest** [comment]
I played around with the inspect tool to try to find some easy header solutions to inject a city name into our current BikeTag layout. With the official evolution of Bike Tag to BikeTag (one word), I'm kinda feeling option C. I just wanted to see if any of these felt right or "right enough for now" to anyone else. These seem like easy changes (correct me if I'm wrong, @KenEucker) to make before we can get a dev/designer to help out with the page template more.

OPTION A (doesn't fit out new BikeTag branding)
![image](https://user-images.githubusercontent.com/65753068/85190362-9426bc00-b26c-11ea-8322-cde724886874.png)

OPTION B (the "less great" option)
![image](https://user-images.githubusercontent.com/65753068/85190368-a0127e00-b26c-11ea-8c56-41312daf5b77.png)

**OPTION C (the best option, IMO)**
![image](https://user-images.githubusercontent.com/65753068/85190370-a4d73200-b26c-11ea-80a5-c1a9e5cfaf72.png)

**Comment by ellenwest** [comment]
FYI @evan-white, Ken is working on implementing OPTION B from my comment above :)

**Comment by KenEucker** [comment]
@ellenwest @evan-white @JackieSul

The site has been updated with work from this ticket and #80.

**Comment by ellenwest** [comment]
This looks great! I really like seeing the city names printed on each subdomain. Nice work!

Some quick QA caught these issues:

1.  Crop of 'Indianapolis' on iPhone viewport
![image](https://user-images.githubusercontent.com/65753068/85195610-de1d9b00-b288-11ea-94fa-48fda81e044a.png)

2. "StLouis" missing a space and a period? (i.e. St. Louis)
![image](https://user-images.githubusercontent.com/65753068/85195626-fdb4c380-b288-11ea-9a0c-8d40e0396841.png)

**Comment by JackieSul** [comment]
Awesome!! This is a great idea, I like seeing the names a lot.

What would it look like if we center aligned and stacked the header?

The spinning bike logo can go above the text ‘city/biketag’ or
‘biketag/city’.  This could clean up the spacing between City Logo BikeTag
 and it will give more space for longer city names.

PS: Indianapolis can always be shortened to ‘Indy’

JS

**Comment by KenEucker** [comment]
<img width="710" alt="Screen Shot 2020-06-27 at 12 44 33 PM" src="https://user-images.githubusercontent.com/1720267/85930791-04889b00-b874-11ea-8d12-5edc13ac4a90.png">

Done!

**Comment by jaquelynesulhoff** [comment]
Looks great!
