### ISSUE TITLE
Add a date for the pictures

### ISSUE THREAD

**Issue by donpdonp** [KenEucker/biketag-website#5]
It'd help to have some indication of the date of the photos. I cant tell if the latest photo is from yesterday or from a year ago. It matters because it'd give a sense that if I participated, there would be others to keep the game going, if I knew that photos changed recently.

**Comment by KenEucker** [comment]
This is a fantastic suggestion! I think we can add this to the UI in some way that doesn't clutter it up, but I'm not sure what route to go at the moment. I can see this being an important feature to many, so thanks for bringing it up!

**Comment by wong-a** [comment]
+1 It would be a great feature to know how long the latest tag was been up for.

**Comment by KenEucker** [comment]
@wong-a I will make sure that this functionality is added to the new [biketag-vue](https://github.com/keneucker/biketag-vue) project which is in active development and should be in alpha release before the end of the year.

The biketag-website project is currently deprioritized, but if anyone provides PRs to this repo to address any existing issues I will take a look at it.

**Comment by KenEucker** [comment]
Dates are in the new BikeTag App.

This biketag-website project is now sunsetting.
