### ISSUE TITLE
BikeTag Game Glossary: Term and Phrase Definitions

### ISSUE THREAD

**Issue by ellenwest** [KenEucker/biketag-website#54]
Define terminology and definitions for things like:
"Tag It"

Choose how we want to refer to geographical expansion, e.g. the implications of choosing the terms region vs city vs town vs greater metro areas, etc. and the boundaries they create.

**Comment by evan-white** [comment]
Here are our first Terms and Phrases for consideration!

-----
BikeTag Terms and Phrases with Definitions:
-----
“BikeTag”: #1 What we title the game (one word). #2 A Bike plus a Tag.

“BikeTag Team”: How we identify ourselves collectively, and how we sign our communications
 
"Tag": The uniquely identifiable object/place in a BikeTag image.

“Image”: A visual representation of a BikeTag.

"Mystery Location": The BikeTag that game players are attempting to find.

“Round”: one of a sequence of related events played in such a way that progress can be seen between each.

"Play": The attempt or act of participating in or advancing the game.

"Play a Round of BikeTag": the correct sequence of two BikeTags played; one that matches the sought mystery location and another that creates a new mystery location. 

#1 “Describe where to find the Mystery Location”: A written description of the Tag at the Mystery Location.

“Hint”: A text-based clue provided by a player that describes either tag and/or mystery location.

Good Examples: Attribute(s) of a BikeTag that meets the current rules of the game.

Bad Examples: Attribute(s) of a Biketag that does not meet the current rules of the game.

-----
Terms and phrases to consider removing from use:
-----

Proof found at (refers to BikeTag found at)

Proof (refers to #1)

Tag it! (Refers to Play a Round of BikeTag)

Thing (refers to an image)

Picture (refers to an image)

Photo or photograph (refers to an image)

**Comment by KenEucker** [comment]
The work already completed on this ticket is sufficient for the need here.

This biketag-website project is now sunsetting.
