### ISSUE TITLE
Add SEO to regional configuration

### ISSUE THREAD

**Issue by ellenwest** [KenEucker/biketag-website#60]
Add meta fields and other SEO fields to the configuration for each individual subdomain as well as the default.

**Comment by KenEucker** [comment]
This has been implemented in both the config.json file in the root, for all routes, as well as the data config for the subdomains which override the default set in the config.json.

> https://github.com/KenEucker/biketag-website/blob/master/config.sample.json

```
	"metaUrl": "http://biketag.org",
	"metaType": "article",
	"metaTitle": "BikeTag!",
	"metaDescription": "BikeTag.org is a place for people to see the most recent Bike Tags in their city and participate in the game in an easy and simple way, without needing to login to anything.",
```

> https://github.com/KenEucker/biketag-website/blob/master/data/config/subdomains.json
```
"portland": {
		"metaTitle": "PortlandBikeTag!",
		"region": "Portland, Oregon",
		"tagline": "The BikeTag game in Portland, Oregon",
```
