### ISSUE TITLE
Create regional email addresses

### ISSUE THREAD

**Issue by ellenwest** [KenEucker/biketag-website#64]
The most pressing aliases to set up are:
* Denver
* Seattle
* Indianapolis

**Comment by KenEucker** [comment]
The rubric we should use for these going forward is:

subdomain.biketag.org@gmail.com.

We should also setup aliases to all of the Gmail accounts using the rubric:
subdomain@biketag.org 

These steps should be added to the ambassadorship playbook(s) in #36.

**Comment by KenEucker** [comment]
This has now become part of the process and is outlined in the [new ambassador checklist document](https://docs.google.com/document/d/1zw8uQ68OHHZFx2hLCpEcCOrXMqjfiLUSY3cXCyPPATA/edit?usp=sharing).
