### ISSUE TITLE
Create develop server with continuous integration

### ISSUE THREAD

**Issue by KenEucker** [KenEucker/biketag-website#66]
With the develop branch, let's set up a remote on a development server that runs continuous integration allowing regional admins to make content changes and see those changes go live on a development server.

After implementing this, the repository should be locked down so that only devs can push to master and create a workflow for pull requests for site content updates using github as the CMS.

**Comment by CalcMan** [comment]
https://www.heroku.com/free can host services for free
consider dockerizing, https://hub.docker.com/ can be configured to pull from a branch and create a public container

**Comment by KenEucker** [comment]
@CalcMan Thanks for the heads up! Dockerizing the project would be really helpful. We'll add that as a someday-maybe ticket! Always open to more people helping out as well!

**Comment by KenEucker** [comment]
We now a have a dev server at https://biketag.dev

Sexpress will need to have an implementation of setting up remotes for deployments that brings this feature to BikeTag.

**Comment by KenEucker** [comment]
This biketag-website project is now sunsetting.
