### ISSUE TITLE
Secure the site with SSL

### ISSUE THREAD

**Issue by KenEucker** [KenEucker/biketag-website#72]
Currently, biketag.org is a web 2.0 http site.

Let's give our site visitors the safety experience they expect and invest in an SSL certificate and serve our web app on https. This requires acquiring an SSL certificate and maintaining that certificate year over year.

**Comment by watchingJu** [comment]
Why does this need funding? In 2020 that should be a non-issue.

**Comment by KenEucker** [comment]
Apparently, @watchingJu, you're correct.

It looks like we can go with letsencrypt for free: https://letsencrypt.org/getting-started/

I'm not sure what you're referring to about a non-issue in 2020, but there's no need to be rude about it.

**Comment by watchingJu** [comment]
Sorry, that should not have sounded rude. I meant it's quite easy to do so (let's encrypt + certbot) and in web dev it's standard to use https on pages that transfer data bi-directional (on others it should be too).

**Comment by KenEucker** [comment]
@watchingJu, I read this as soon as I woke up and took it wrong. I apologize.

I'm implementing SSL now. I think, originally, I was thinking about SSL for e-commerce and the expense of the SSL certificates in use for enterprise websites.

**Comment by KenEucker** [comment]
@watchingJu the site now runs on https using a letscrypt SSL cert. 

I'm not currently enforcing https, as I need to continue to support http for previously used links out in the world. There may soon be a way to redirect all traffic to https, for now we'll run both side by side.

Thanks for commenting.

**Comment by watchingJu** [comment]
@KenEucker Thanks for fixing that :)

You should always enforce https. To handle legacy links you can do a redirect (rewrite) with htaccess. There are some easy solutions on stackoverflow (but I have too little knowledge to recommend a specific  one :/ ).

**Comment by KenEucker** [comment]
@watchingJu YW. We discussed this over the past week and I'm hoping there's a benefit I'm not seeing but I should add a bit not clarity for documentation sake:

There's no bi-direction data transfer going on with the client (browser) and BikeTag.Org outside of retrieving the imgur authorization token used to upload to imgur. When a user submits a new tag, the information is sent directly to imgur, on what should have already been a secure connection. 

The app has no database and outside of the request for imgur authorization, which is stored in memory on the server, the app makes no other requests to the server. Everything is open. The imgur album is public. The content and configuration for the website is all public. 

Nevertheless, everything should be https. Redirecting all traffic to https will come soon.
