### ISSUE TITLE
How-to section with story design

### ISSUE THREAD

**Issue by evan-white** [KenEucker/biketag-website#79]
In updating the how-to section of the game we are going with a story card format.

**Comment by evan-white** [comment]
Here is a first 
![Howto page 2 (draft)](https://user-images.githubusercontent.com/64663106/83182385-222edd00-a0db-11ea-88d3-a5254853c13d.png)
![Howto page 1 (draft)](https://user-images.githubusercontent.com/64663106/83182394-25c26400-a0db-11ea-8da6-244ff46d42da.png)

draft of what story cards could look like.

**Comment by KenEucker** [comment]
When we first discussed this, I had envisioned something less verbose with more images/icons. I like the mural == good, dumpster fire == bad idea. 

What I was originally thinking, and we don't necessarily have to go this route, was something that is story/card based that is identical to what users would see when submitting a new tag with the exception that the how-to story and Instagram story would not show the form fields that would be present on the Tag IT form. #69 is the ticket for the development of the form and I was looking to integrate the story as the base for the form and then simply add the image uploads and textboxes.

@evan-white, does what I'm envisioning make sense?

**Comment by ellenwest** [comment]
In our meeting today, you brought up the great point that it might help reduce user frustration to state something to the effect of:

Rounds can be played quickly. Do it for the ride and don’t be sad if someone else beats you to it. You’re still a winner.

**Comment by evan-white** [comment]
Looking to collaborate with Jackie on this design and circle back in on week.

**Comment by evan-white** [comment]
After much deliberation, presenting the first version of the "How-To Guide"!



-----
Card 1 - How BikeTag Works (Summary Card)
-----
Biketag is a photo tag game where you find a mystery location in the real world by bicycle.

To play the game you need to understand these three things:
Images of bikes and unique things together are what we call “BikeTags”.
 The object of the game is to find and create what we call “Mystery Locations”.
The game never ends and every round is a new chance to play the game.
((Use the thing-we-need-to-choose (Like arrows, or swipe) to navigate this how-to guide.))
-----
Card 2 - Gameplay (Finding the current Mystery Location)
-----
The place where the most recent BikeTag was made is called the “Mystery Location”.
In this example, an orange-colored bike is shown: 
![Current Mystery Location V1](https://user-images.githubusercontent.com/64663106/87178616-45c87400-c292-11ea-9450-dada6e343342.png)
-----
Card 3 - Gameplay (Creating a matching BikeTag)
-----
Once you arrive at the Mystery Location you must create a matching BikeTag image of your own. In this example, you are the blue colored bike:
![Matching BikeTag Image V1](https://user-images.githubusercontent.com/64663106/87178651-537df980-c292-11ea-9e9f-713723cb25b6.png)
-----
Card 4 - Gameplay (Creating a new BikeTag) 
-----
Next, it’s time to ride to a new Mystery Location and make a new BikeTag. 
![New BikeTag V1](https://user-images.githubusercontent.com/64663106/87178669-5f69bb80-c292-11ea-9fda-d036611ffc1d.png)
Keep in mind, good Mystery Locations help progress the game.
-----
Card 4 - The Mystery Location Explained (good/bad) 
-----
Great Mystery Locations have unique, interesting, and identifiable things. Think about where you want to go and choose wisely to keep the game running smoothly.
![Card 4](https://user-images.githubusercontent.com/64663106/87178897-bd969e80-c292-11ea-811f-fdc27c5e3e5d.png)
Great examples include created objects like murals and buildings, and permanent objects like landmarks and natural features.

-----
Card 5 - The Mystery Location Continued
-----
Not-so-great Mystery Locations are featureless, obscure, and are inaccessible. They shouldn’t be hard to find. Don’t create a BikeTag that is unsafe for others. 
![Card 5](https://user-images.githubusercontent.com/64663106/87178949-d010d800-c292-11ea-8a21-294f5921b63d.png)
Not-so-great examples include temporary and moving objects like food trucks and graffiti, plain objects like concrete walls, and private property that would require trespassing. Remember, pick locations that help advance the game.

-----
Card - 6 Submission Form
-----
For the game to advance you will need to play your matching and new BikeTags! From the main page tap on “Play The Next Round”. Fill out the form: 
Upload your matching and new BikeTag images.
Create a hint to help other players find your Mystery Location.
Choose a name to credit yourself or your group. (This can be a nickname, team name, @Instagram or u/Reddit, anything!)
Tap on “Play Biketag” to complete a round of the game. 
-----
Card 7 - Thanks for playing BikeTag!
-----
Thanks for playing BikeTag!!!

(slideshow style animated gif collage of Biketags)
 
More questions? 
Email us at: hello@biketag.org
Do it for the ride!
Support us by buying some BikeTag Merchandise
Bike. Discover. Share.

**Comment by evan-white** [comment]
![e673441d-61dd-4b8c-83d3-97ec2df9eed5](https://user-images.githubusercontent.com/64663106/94867063-53a31680-03f5-11eb-8d3a-8a58b486fc6e.jpeg)
![890b139d-655c-498b-b3c6-1194a1c06afd](https://user-images.githubusercontent.com/64663106/94867066-556cda00-03f5-11eb-9e2b-fc00a2bb0523.jpeg)
![aeb7709c-1ba7-41bb-97dc-03ac24991a55](https://user-images.githubusercontent.com/64663106/94867070-569e0700-03f5-11eb-9082-e6847986b5ee.jpeg)
![22d61d93-a33d-4168-9166-1225fe5fe1cc](https://user-images.githubusercontent.com/64663106/94867074-57cf3400-03f5-11eb-812e-2133aba73b32.jpeg)

**Comment by ellenwest** [comment]
Jackie will try matching the body font to what we have on the web; font name is Lato.

**Comment by KenEucker** [comment]
Leaving this here to come back to it later:

https://github.com/ramon82/zuck.js

**Comment by KenEucker** [comment]
This has been implemented in the new BikeTag App.
