### ISSUE TITLE
Tag Submission Form: rename form fields, pre-fill placeholder/hint text

### ISSUE THREAD

**Issue by ellenwest** [KenEucker/biketag-website#80]
![image](https://user-images.githubusercontent.com/65753068/83227338-ce52e100-a138-11ea-9d8e-394935a4d23d.png)

**Comment by ellenwest** [comment]
These are just some suggestions of how we can adjust form labels to remove user confusion around the information we're trying to collect by getting rid of jargon like "Proof". The goal is to make it so that anyone can open up the form and easily play. We can also add pre-fill placeholder text withing fields to give an example of how to fill out form fields.

The copy needs some wordsmithing but wanted to spitball on whether or not we agree on these sorts of changes improve the UX.

"PROOF FOR #209"
**Change to:** "Did you find Tag #209?"

IMAGE PROOF YOU FOUND THE MYSTERY LOCATION > 
**Change to:** "Upload a picture of your bike at Tag #209"/"Upload a picture of your bike at the current Tag"

LOCATION OF THE LAST TAG: 
**Change to:** "Where did you find this Tag? (Place name, intersection, etc.)"
Pre-filled text: _"e.g. Cathedral Park, NE 42nd and Shaver, etc."_

NEXT TAG (#210)
**Change to:**  "Your chosen mystery location for the next Tag"/"Choose a mystery location for the next Tag"

IMAGE OF THE NEXT TAG LOCATION
** Change to:**  "Picture of your bike in mystery location"

HINT FOR THE NEXT TAG LOCATION:
** Change to:** "Give us a hint about the mystery location. Note: We only post this if our community gets stumped!".

hint
** Change to:** "e.g. Stop here to get a lager on your way to Cathedral Park, etc."

WHAT DO YOU GO BY?
**Change to:** "What name would you like to credit the Tag to? Note: If you are a Reddit user, you can link the Tag to your profile by using the format /u/<your username>"/"What do you want to known by in our Tag community?"

name
**Change to:** "e.g. The Spokes Person, Cyclopath, Karen, etc."

TAG IT!
**Change to:**  (no suggested changes)

**Questions**: 
1. Do we want to include our link to the Code of Conduct or Instructions on How to Play here?
2. Can we adjust the modal so that a click outside of it no longer triggers the modal to close?

**Comment by evan-white** [comment]
@ellenwest, these are great ideas. I'll be tying this issue to #79 and #54. I'm working on creating a set of formal definitions we will begin using to address these clarity issues and hopefully reduce confusion.

**Comment by evan-white** [comment]
Here is an updated draft that exclusively uses terms and phrases from #54 

"PROOF FOR #209"
Change to: "Did you find Mystery Location played for round #209?"
IMAGE PROOF YOU FOUND THE MYSTERY LOCATION >
Change to: "Play a BikeTag that matches Biketag round #209 here"
LOCATION OF THE LAST TAG:
Change to: "Describe where to find the Mystery Location"
Pre-filled text: "e.g. Cathedral Park, NE 42nd and Shaver, etc."
NEXT TAG (#210)
Change to: "Play a new BikeTag Mystery Location."
IMAGE OF THE NEXT TAG LOCATION
Change to: "Play a new BikeTag Mystery Location here"
HINT FOR THE NEXT TAG LOCATION:
Change to: "Provide a hint for the new Mystery Location".
Pre-filled text: "e.g. puns, riddles, rhymes, nearby landmarks, where historical events occurred."
WHAT DO YOU GO BY?
Change to: "Provide a Name”.
Pre-filled text: "e.g. Your Reddit or Instagram handle, nickname, team name, real name".
TAG IT!
Change to: Play BikeTag!

**Comment by evan-white** [comment]
Here is a design draft for how a card-style BikeTag submission form could look. This also uses terms and definitions from #54 


Card 1: Play BikeTag!
Order of steps:
Show image #200
Provide a description
Play a matching image
-----
Play BikeTag! Did you find the Mystery Location played for Round #200?:
-----
Describe where to find the Mystery Location: 
Goal: Display an Image of BikeTag #200
[Text box for the user to enter a text description]
Goal: A “Check” symbol appears next to the text box once a submission is entered.

Play a BikeTag that matches BikeTag #200. Make sure that it follows the Good Examples.
Goal: Make Good Examples sidebar to the good examples card from the how-to section.
(User is provided with an upload dialog box) 
Goal: Uploaded matching BikeTag Image #200 displays on this card.

Card 2: Create a new Mystery Location
Order of steps:
Play a new image
Provide a hint
Provide a name
-----
Begin Round #201. Create a new Mystery Location: 
-----
Play a new BikeTag Mystery Location. Make sure that it follows the Hint Examples.
Goal: make Hint Examples sidebar to the hint examples card from the how-to section.
(User is provided with an upload dialog box) 
Goal: uploaded new BikeTag Image #201 displays on this card.

Provide a Hint for the new Mystery Location:
[Text box for the user to enter a text description]
Goal: Check symbol appears next to the text box after user submission is entered.

Provide a Name: Check out all of the ways you can claim your BikeTag 
[Text box for the user to enter a text description]
Goal: Check symbol appears next to the text box after user submission is entered.

Card 3: Confirm and Play the next Round
Order of steps:
Display name
Display hint
Display new image #201
Display matching image #200
Display description
Display image #200
-----
Confirm and Play the next Round:
-----
You are: Display text from Name text box
The hint you are providing is: Display text from the Hint text box
Your Biketag Image of the new mystery location is:
Goal: uploaded new BikeTag Image #201 displays on this card.
Your matching BikeTag Image is:
Goal: uploaded matching BikeTag Image #200 displays on this card.
You found the last Mystery Location at: Display text from the Mystery Location text box
The last Mystery Location was:
Goal: Display an Image of #200

**Comment by ellenwest** [comment]
Fabulous, @evan-white! Thanks so much for getting this all fixed up with the official terminology!

**Comment by KenEucker** [comment]
![Screen Shot 2020-06-19 at 1 42 27 PM](https://user-images.githubusercontent.com/1720267/85178262-e77c1880-b232-11ea-9022-c8fb81897c27.png)

^ Quick implement of this.

**Comment by KenEucker** [comment]
@evan-white @ellenwest @JackieSul

Final pass on this new redesign of the form:
![biketag-new-form-design-blank](https://user-images.githubusercontent.com/1720267/85213730-1ec3f580-b317-11ea-9d7c-b8073fcc4095.png)
![biketag-new-form-design](https://user-images.githubusercontent.com/1720267/85213727-14096080-b317-11ea-92bf-b2f3fafeeebd.png)

I believe that this closes this ticket out, but I am open to more feedback. I know that there's more work to be done with fonts and colors being done in issue #96. Not all of that needs to be flushed out for this issue to be completed.

**Comment by JackieSul** [comment]
A++

**Comment by KenEucker** [comment]
And, we're done!

**Comment by jaquelynesulhoff** [comment]
Hooray!
