### ISSUE TITLE
Upgrade from web app to a hybrid or progressive web app 

### ISSUE THREAD

**Issue by ellenwest** [KenEucker/biketag-website#90]
To make sure we're all on the same page, lets define some terminology:

1. **[WHAT WE KIND OF HAVE NOW] Web app**  - a responsive, mobile-friendly website that is designed with a mobile-first approach
- CON: requires a browser to load and for the user to have to navigate to the URL. This can be a clunky mobile UX.
2. **[NOT A FEASIBLE OPTION]  Native app** - the most common type of app; what you see when you search an app store. 
- CON : requires native programming languages like (not HTML, CSS, JS) for both Android and iOS platforms. This makes them expensive to build.
3. **[OPTION 1] Hybrid app** - uses web technologies (HTML, CSS, JS) just like a website site but exists inside a container or framework that makes it appear to be a native app. You only need a single app for all platforms. You can convert your responsive HTML5 websites into mobile apps with the help of a tool called Apache Cordova.
- CON : usually slower than native apps
4. **[OPTION 2] Progressive Web App (PWA)**: These apps are not the real app but an extension(shortcut) to a website/webpage. 
 - POSSIBLE CON: They are added to the Homescreen of your mobile device with a browser option of ‘Add To Homescreen‘. PWAs do not exist in app stores like Google Play or Apple's App Store.

**Comment by KenEucker** [comment]
What about those new live apps? Like Amazons? Where it doesn't need to install but opens upon a link?

**Comment by KenEucker** [comment]
The new BikeTag App is a PWA.

This biketag-website project is now sunsetting.
