### ISSUE TITLE
COVID banner

### ISSUE THREAD

**Issue by ellenwest** [KenEucker/biketag-website#97]
Post a one day banner on the site that states our code of conduct around inclusion and following the recommended social distancing guidelines.

**Comment by ellenwest** [comment]
Our final banner verbiage is "BikeTag asks you to play responsibly on [Pedalpalooza Scavenger Hunt Day](pedalpalooza.org) by wearing masks and staying two bikes apart."

**Comment by KenEucker** [comment]
This is no longer running, as we are outside of the Pedalpalooza increase in traffic to the website. At any point we feel we need to turn this banner on again, we can.
