### ISSUE TITLE
Sound-producing spoke cards

### ISSUE THREAD

**Issue by ellenwest** [KenEucker/biketag-website#98]
We could create a special edition of spoke cards from a custom deck of Bike Tag playing cards -- the goal of this spoke card is to create sound when riding (e.g. ppfffbbbllll pfffbbbllll pfffblll PFFFFBLLLL)

**Comment by evan-white** [comment]
Cards ordered! Horrible Logos general logoed poker playing cards. Estimated arrival July 1.

**Comment by KenEucker** [comment]
This biketag-website project is now sunsetting.
